### ISSUE TITLE
Missing /usr/share/libvirt/cpu_map.xml

### ISSUE THREAD

**Issue by fuerst** [jeffreywildman/homebrew-virt-manager#15] opened 2015-06-08 12:27 UTC
When trying a `qemu+ssh://..` URI I get the following error:

    [Errno 2] No such file or directory: '/usr/share/libvirt/cpu_map.xml'

Symlinking this file from `/usr/local/Cellar/libvirt/1.2.16/share/libvirt/cpu_map.xml` to `/usr/share/libvirt/cpu_map.xml` does fix this. I wonder how anyone used Virt manager without this symlink. Did I miss something during installation?

The path of this file is hard coded in `/usr/local/Cellar/virt-manager/1.2.0/libexec/share/virt-manager/virtinst/capabilities.py:55`. May be it should be patched during installation?

**Comment by jeffreywildman** [comment] 2015-06-08 15:25
Thanks!  I think the issue is that the virt-manager installation currently expects libvirt to be installed in system directories (`/usr/bin`, `/usr/share`, etc.), when in fact it is installed into homebrew directories (`/usr/local/bin`, `/usr/local/share`, etc.).  The referenced `capabilities.py` should actually be looking at `/usr/local/share/libvirt/cpu_map.xml`.  A patch as you suggested should work, especially if it is truly hard-coded, but I am also curious to see if virt-manager provides an install option to instruct it on where to look for libvirt-related files.

Btw, it looks like this issue is in reference to the `virt-install` command.  I've not actually used/tested this command, and I'd wager most users have been using `virt-manager` and `virt-viewer` which avoids touching `cpu_map.xml`.

**Comment by fuerst** [comment] 2015-06-08 19:09
See here for some info about this bug in libvirt: https://bugzilla.redhat.com/show_bug.cgi?id=916786

I got this error using _virt-manager_, not _virt-install_. Nevertheless I'm wondering why I'm the only one to encounter this bug yet.

**Comment by jeffreywildman** [comment] 2015-06-08 20:42
Thanks for the link.  I also found this discussion to be relevant: https://www.redhat.com/archives/virt-tools-list/2014-January/msg00254.html.  Interesting indeed on your observation.

I've pushed a [dev](https://github.com/jeffreywildman/homebrew-virt-manager/tree/dev) branch which updates the location of `cpu_map.xml`, if you have a moment, could you confirm if this fixes the issue and/or opens up new ones?

**Comment by fuerst** [comment] 2015-06-09 07:35
It seems to fix this, thanks! No more cpu_map.xml related errors.

**Comment by jeffreywildman** [comment] 2015-06-09 17:52
Closed by b1ae14ec.

**Closed by jeffreywildman** 2015-06-09 17:52 UTC
