### ISSUE TITLE
Installation fails: Missing type converters

### ISSUE THREAD

**Issue by alvassin** [jeffreywildman/homebrew-virt-manager#71] opened 2017-06-14 18:42 UTC
Details:
```
$ brew install virt-manager virt-viewer
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (caskroom/versions, homebrew/core).
==> Updated Formulae
davmail

==> Installing virt-manager from jeffreywildman/virt-manager
==> Downloading https://virt-manager.org/download/sources/virt-manager/virt-manager-1.4.1.tar.gz
Already downloaded: /Users/alvassin/Library/Caches/Homebrew/virt-manager-1.4.1.tar.gz
==> Patching
patching file virt-clone
patching file virt-convert
patching file virt-install
patching file virt-manager
patching file virt-xml
==> Downloading https://libvirt.org/sources/python/libvirt-python-3.0.0.tar.gz
Already downloaded: /Users/alvassin/Library/Caches/Homebrew/virt-manager--libvirt-python-3.0.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/virt-manager/1.4.
Last 15 lines from /Users/alvassin/Library/Logs/Homebrew/virt-manager/01.python:
running install
running build
/usr/local/opt/pkg-config/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
/usr/local/opt/python/bin/python2.7 generator.py libvirt /usr/local/Cellar/libvirt/3.4.0/share/libvirt/api/libvirt-api.xml
Found 425 functions in /usr/local/Cellar/libvirt/3.4.0/share/libvirt/api/libvirt-api.xml
Found 0 functions in libvirt-override-api.xml
Generated 348 wrapper functions
Missing type converters:
virStreamSinkFunc:1
long long *:1
virStreamSourceFunc:1
ERROR: failed virStreamRecvHole
ERROR: failed virStreamSparseRecvAll
ERROR: failed virStreamSparseSendAll
error: command '/usr/local/opt/python/bin/python2.7' failed with exit status 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
brew install virt-manager issue https://github.com/jeffreywildman/homebrew-virt-manager/issues/58
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62
```

Can you advice workaround please? virt-viewer installs successfully.

**Comment by deanrock** [comment] 2017-06-19 17:30
virt-manager installed from #70 seems to work fine (at least with --no-fork flag).

**Comment by alvassin** [comment] 2017-06-20 08:21
When using @Ufflo fork, installation succeeds, but then when executing following command it fails (I have pygobject3 installed using brew):
```
$ virt-manager -c qemu+ssh://alvassin@10.248.0.5/system?socket=/var/run/libvirt/libvirt-sock --no-fork
  File "/usr/local/Cellar/virt-manager/1.4.1/libexec/share/virt-manager/virt-manager", line 47
    print "pygobject3 3.14.0 or later is required."
                                                  ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by jonathangilpin** [comment] 2017-06-21 08:36
vi /usr/local/Homebrew/Library/Taps/jeffreywildman/homebrew-virt-manager/virt-manager.rb

change:
url "https://libvirt.org/sources/python/libvirt-python-3.0.0.tar.gz"
to
url "https://libvirt.org/sources/python/libvirt-python-3.4.0.tar.gz"

and
sha256 "94a7c1c57a643afad43f9068c70774e1146ed051ecfca0280d5127011c5e44c1"
to
sha256 "afa77781f518988f164dd5f99d1844034ca807a8e731e07cbae18474d250b511"

and it will then install however it will crash when you run it, unless you run with the argument ---debug

**Comment by jeffreywildman** [comment] 2018-02-25 02:15
Duplicate of #90.

**Closed by jeffreywildman** 2018-02-25 02:15 UTC
