### ISSUE TITLE
Request: document where settings are stored

### ISSUE THREAD

**Issue by seanhoughton** [jeffreywildman/homebrew-virt-manager#130] opened 2019-07-09 05:10 UTC
I've been searching every corner of the internet trying to figure out where the list of stored connections is loaded from. I tried looking through the source code but it seems to want to store configs at

```py
self.conf_dir = "/org/virt-manager/%s/" % self.appname
```

which is not valid on MacOS.

**Comment by jeffreywildman** [comment] 2019-07-13 13:44
Duplicate of #61

**Closed by jeffreywildman** 2019-07-13 13:44 UTC

**Comment by klepek** [comment] 2020-02-14 14:37
@seanhoughton , in #61 there is answer to your question
