### ISSUE TITLE
Installation fails: Missing type converters: unsigned long long *:1 ERROR: failed virDomainMigrateGetMaxDowntime

### ISSUE THREAD

**Issue by miradam** [jeffreywildman/homebrew-virt-manager#80] opened 2017-09-05 10:07 UTC
Hi, I'm having similar issue to already reported one although mine is bit different.
I'm receiving the following error:
Missing type converters:
unsigned long long *:1
ERROR: failed virDomainMigrateGetMaxDowntime
error: command '/usr/bin/python' failed with exit status 1

I have the following packages defined in /usr/local/Homebrew/Library/Taps/jeffreywildman/homebrew-virt-manager/virt-manager.rb 
-- snip
url "https://virt-manager.org/download/sources/virt-manager/virt-manager-1.4.1.tar.gz"
sha256 "e6c549999f14fbda210c07821910bfa35c086542e166f8b00d7c83717e9f3944"
url "https://libvirt.org/sources/python/libvirt-python-3.4.0.tar.gz"
sha256 "afa77781f518988f164dd5f99d1844034ca807a8e731e07cbae18474d250b511"
-- snip
Any ideas?

**Comment by evansharp** [comment] 2017-09-18 20:52
Me too...

**Comment by mplessard** [comment] 2017-09-19 18:15
Same for me here

**Comment by royceniu** [comment] 2017-09-22 14:16
Same here +1

**Comment by miniCruzer** [comment] 2017-10-06 03:03
Same.

```
$  brew install virt-manager
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

==> Installing virt-manager from jeffreywildman/virt-manager
==> Downloading https://virt-manager.org/download/sources/virt-manager/virt-manager-1.4.1.tar.gz
Already downloaded: /Users/sam/Library/Caches/Homebrew/virt-manager-1.4.1.tar.gz
==> Patching
patching file virt-clone
patching file virt-convert
patching file virt-install
patching file virt-manager
patching file virt-xml
==> Downloading https://libvirt.org/sources/python/libvirt-python-3.4.0.tar.gz
Already downloaded: /Users/sam/Library/Caches/Homebrew/virt-manager--libvirt-python-3.4.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/virt-manager/1.4.1/libexec/vendor --single-version-externally-managed --record=ins
Last 15 lines from /Users/sam/Library/Logs/Homebrew/virt-manager/01.python:
--prefix=/usr/local/Cellar/virt-manager/1.4.1/libexec/vendor
--single-version-externally-managed
--record=installed.txt

running install
running build
/usr/local/opt/pkg-config/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
/usr/bin/python generator.py libvirt /usr/local/Cellar/libvirt/3.8.0/share/libvirt/api/libvirt-api.xml
Found 428 functions in /usr/local/Cellar/libvirt/3.8.0/share/libvirt/api/libvirt-api.xml
Found 0 functions in libvirt-override-api.xml
Generated 348 wrapper functions
Missing type converters:
unsigned long long *:1
ERROR: failed virDomainMigrateGetMaxDowntime
error: command '/usr/bin/python' failed with exit status 1
```

I'm sorta new to virt-manager, but `/usr/bin/python` is Python 2.7.10 which is the one exiting with status 1, and I see its trying to download Python 3.4.0 as well.

**Comment by jfargen** [comment] 2017-11-13 16:17
Facing the same issue with HighSierra 10.13. Please find the output of the issue in the attached file brew-virt-manager-issue.txt.


[brew-virt-manager-issue.txt](https://github.com/jeffreywildman/homebrew-virt-manager/files/1467558/brew-virt-manager-issue.txt)

**Comment by aboullaite** [comment] 2017-11-21 12:19
Upgrading `libvirt-python-3.7.0` instead of `libvirt-python-3.4.0` to solved the issue:

go to `/usr/local/Homebrew/Library/Taps/jeffreywildman/homebrew-virt-manager/virt-manager.rb` and update:
```
  resource "libvirt-python" do
    url "https://libvirt.org/sources/python/libvirt-python-3.7.0.tar.gz"
    sha256 "1e4a8a8b08ef8f2502088f26ce3aced415d55ef808d8301dfed023f45154c06f"
  end
```

**Comment by gauravojha** [comment] 2018-02-20 16:44
@aboullaite  Thank you so much! This worked great

**Comment by jeffreywildman** [comment] 2018-02-25 02:19
Duplicate of #90, resolved.

**Closed by jeffreywildman** 2018-02-25 02:19 UTC
