### ISSUE TITLE
Unable to use keymap in virt-viewer

### ISSUE THREAD

**Issue by suns1824** [jeffreywildman/homebrew-virt-manager#134] opened 2019-08-12 15:53 UTC
When I connect my vm, the console prints the following msg:
Unsupported GDK Windowing platform.
Disabling extended keycode tables.
Please report to gtk-vnc-list@gnome.org
including the following information:
  - Operating system
  - GDK Windowing system build

My MacOs is 10.14.6,my gtk+3 is 3.24,I have installed xquartz manually and my gtk-vnc is 0.9.0,I have used many ways to fix it ,but it does not work.Can you give me any idea? Thank U.

**Comment by brando56894** [comment] 2019-08-16 08:14
I just switched to a new Macbook at work and I can confirm the same behavior

```
(remote-viewer:51707): vnc-keymap-WARNING **: 04:02:59.875: Unsupported GDK Windowing platform.
Disabling extended keycode tables.
Please report to gtk-vnc-list@gnome.org
including the following information:

  - Operating system
  - GDK Windowing system build


(remote-viewer:51707): GSpice-WARNING **: 04:03:13.523: Warning no automount-inhibiting implementation available

(remote-viewer:51707): GSpice-CRITICAL **: 04:03:16.951: send_key: assertion 'scancode != 0' failed
```

**Comment by jeffreywildman** [comment] 2019-09-01 15:23
Duplicate of #135

**Closed by jeffreywildman** 2019-09-01 15:23 UTC
Labels: duplicate
