### ISSUE TITLE
Missing type converters: unsigned long long *:1 ERROR: failed virDomainMigrateGetMaxDowntime error: command '/usr/bin/python' failed with exit status 1

### ISSUE THREAD

**Issue by rzlrogerio** [jeffreywildman/homebrew-virt-manager#84] opened 2017-09-23 17:08 UTC
These open issues may also help:
brew install virt-manager issue https://github.com/jeffreywildman/homebrew-virt-manager/issues/58
virt-manager silently quits at launch https://github.com/jeffreywildman/homebrew-virt-manager/issues/78
installation failure for virt-manager https://github.com/jeffreywildman/homebrew-virt-manager/issues/72
Error: jeffreywildman/virt-manager/libvirt-glib 1.0.0 did not build https://github.com/jeffreywildman/homebrew-virt-manager/issues/79
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62
Add necessary quotes https://github.com/jeffreywildman/homebrew-virt-manager/pull/75
ERROR: failed virDomainMigrateGetMaxDowntime error: command '/usr/bin/python' failed with exit status 1 https://github.com/jeffreywildman/homebrew-virt-manager/issues/81
Installation fails: Missing type converters: unsigned long long *:1 ERROR: failed virDomainMigrateGetMaxDowntime https://github.com/jeffreywildman/homebrew-virt-manager/issues/80
enable audio/video streaming; overhaul build https://github.com/jeffreywildman/homebrew-virt-manager/pull/83
missing module gi https://github.com/jeffreywildman/homebrew-virt-manager/issues/76
gi has no attribute 'require_version' https://github.com/jeffreywildman/homebrew-virt-manager/issues/74
Installation fails: Missing type converters https://github.com/jeffreywildman/homebrew-virt-manager/issues/71
Unable to connect to libvirt https://github.com/jeffreywildman/homebrew-virt-manager/issues/63
Unable to paste from host to client. Copying from client to host works. https://github.com/jeffreywildman/homebrew-virt-manager/issues/35
Can't install libvirt-python on El Capitan https://github.com/jeffreywildman/homebrew-virt-manager/issues/50
libvirt connection URI ?socket string https://github.com/jeffreywildman/homebrew-virt-manager/issues/61
Install error: failed virConnectNodeDeviceEventRegisterAny https://github.com/jeffreywildman/homebrew-virt-manager/issues/57
 libvirt-glib wont build - OSError: [Errno 1] Operation not permitted: g-ir-scanner/ https://github.com/jeffreywildman/homebrew-virt-manager/issues/82
Create new virtual machine OS types missing https://github.com/jeffreywildman/homebrew-virt-manager/issues/64
Error: configure: error: libjpeg not found https://github.com/jeffreywildman/homebrew-virt-manager/issues/49
after brew update  , the same error https://github.com/jeffreywildman/homebrew-virt-manager/issues/55
Crash on re-open VNC console https://github.com/jeffreywildman/homebrew-virt-manager/issues/44
Fresh install on 10.11.1: fatal error: 'glib/gi18n-lib.h' file not found https://github.com/jeffreywildman/homebrew-virt-manager/issues/30
Install error: [LibvirtGLib-1.0.gir] Error 1 https://github.com/jeffreywildman/homebrew-virt-manager/issues/77
Unable to install due to missing six python module. https://github.com/jeffreywildman/homebrew-virt-manager/issues/68
Python quit unexpectedly every time I try and select a drop down box. https://github.com/jeffreywildman/homebrew-virt-manager/issues/45
Docs update about remote connections https://github.com/jeffreywildman/homebrew-virt-manager/issues/42
Error installing spice-gtk: No package 'spice-client-glib-2.0' found https://github.com/jeffreywildman/homebrew-virt-manager/issues/56

**Comment by petersm1** [comment] 2017-09-25 07:38
Same issue here ....
`peter:~ peter$ brew upgrade virt-manager
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
libnatpmp

==> Upgrading 1 outdated package, with result:
jeffreywildman/virt-manager/virt-manager 1.4.1
==> Upgrading jeffreywildman/virt-manager/virt-manager
==> Downloading https://virt-manager.org/download/sources/virt-manager/virt-manager-1.4.1.tar.gz
Already downloaded: /Users/peter/Library/Caches/Homebrew/virt-manager-1.4.1.tar.gz
==> Patching
patching file virt-clone
patching file virt-convert
patching file virt-install
patching file virt-manager
patching file virt-xml
==> Downloading https://libvirt.org/sources/python/libvirt-python-3.4.0.tar.gz
Already downloaded: /Users/peter/Library/Caches/Homebrew/virt-manager--libvirt-python-3.4.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/virt-manager/1.4.1/libexec/vendor --single-version-externally-managed --record=installed.txt
Last 15 lines from /Users/peter/Library/Logs/Homebrew/virt-manager/01.python:
--prefix=/usr/local/Cellar/virt-manager/1.4.1/libexec/vendor
--single-version-externally-managed
--record=installed.txt

running install
running build
/usr/local/opt/pkg-config/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
/usr/bin/python generator.py libvirt /usr/local/Cellar/libvirt/3.7.0/share/libvirt/api/libvirt-api.xml
Found 428 functions in /usr/local/Cellar/libvirt/3.7.0/share/libvirt/api/libvirt-api.xml
Found 0 functions in libvirt-override-api.xml
Generated 348 wrapper functions
Missing type converters:
unsigned long long *:1
ERROR: failed virDomainMigrateGetMaxDowntime
error: command '/usr/bin/python' failed with exit status 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
brew install virt-manager issue https://github.com/jeffreywildman/homebrew-virt-manager/issues/58
virt-manager silently quits at launch https://github.com/jeffreywildman/homebrew-virt-manager/issues/78
installation failure for virt-manager https://github.com/jeffreywildman/homebrew-virt-manager/issues/72
Error: jeffreywildman/virt-manager/libvirt-glib 1.0.0 did not build https://github.com/jeffreywildman/homebrew-virt-manager/issues/79
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62
Add necessary quotes https://github.com/jeffreywildman/homebrew-virt-manager/pull/75
Missing type converters: unsigned long long *:1 ERROR: failed virDomainMigrateGetMaxDowntime error: command '/usr/bin/python' failed with exit status 1 https://github.com/jeffreywildman/homebrew-virt-manager/issues/84
ERROR: failed virDomainMigrateGetMaxDowntime error: command '/usr/bin/python' failed with exit status 1 https://github.com/jeffreywildman/homebrew-virt-manager/issues/81
Installation fails: Missing type converters: unsigned long long *:1 ERROR: failed virDomainMigrateGetMaxDowntime https://github.com/jeffreywildman/homebrew-virt-manager/issues/80
enable audio/video streaming; overhaul build https://github.com/jeffreywildman/homebrew-virt-manager/pull/83
missing module gi https://github.com/jeffreywildman/homebrew-virt-manager/issues/76
gi has no attribute 'require_version' https://github.com/jeffreywildman/homebrew-virt-manager/issues/74
Installation fails: Missing type converters https://github.com/jeffreywildman/homebrew-virt-manager/issues/71
Unable to connect to libvirt https://github.com/jeffreywildman/homebrew-virt-manager/issues/63
Unable to paste from host to client. Copying from client to host works. https://github.com/jeffreywildman/homebrew-virt-manager/issues/35
Can't install libvirt-python on El Capitan https://github.com/jeffreywildman/homebrew-virt-manager/issues/50
libvirt connection URI ?socket string https://github.com/jeffreywildman/homebrew-virt-manager/issues/61
Install error: failed virConnectNodeDeviceEventRegisterAny https://github.com/jeffreywildman/homebrew-virt-manager/issues/57
 libvirt-glib wont build - OSError: [Errno 1] Operation not permitted: g-ir-scanner/ https://github.com/jeffreywildman/homebrew-virt-manager/issues/82
Create new virtual machine OS types missing https://github.com/jeffreywildman/homebrew-virt-manager/issues/64
Error: configure: error: libjpeg not found https://github.com/jeffreywildman/homebrew-virt-manager/issues/49
after brew update  , the same error https://github.com/jeffreywildman/homebrew-virt-manager/issues/55
Crash on re-open VNC console https://github.com/jeffreywildman/homebrew-virt-manager/issues/44
Fresh install on 10.11.1: fatal error: 'glib/gi18n-lib.h' file not found https://github.com/jeffreywildman/homebrew-virt-manager/issues/30
Install error: [LibvirtGLib-1.0.gir] Error 1 https://github.com/jeffreywildman/homebrew-virt-manager/issues/77
Unable to install due to missing six python module. https://github.com/jeffreywildman/homebrew-virt-manager/issues/68
Python quit unexpectedly every time I try and select a drop down box. https://github.com/jeffreywildman/homebrew-virt-manager/issues/45
Docs update about remote connections https://github.com/jeffreywildman/homebrew-virt-manager/issues/42
Error installing spice-gtk: No package 'spice-client-glib-2.0' found https://github.com/jeffreywildman/homebrew-virt-manager/issues/56

**Comment by r0ndL** [comment] 2017-10-02 19:53
Same issue here (Mac High Siera):
iMac:~ username$ brew install virt-manager virt-viewer
==> Installing virt-manager from jeffreywildman/virt-manager
==> Downloading https://virt-manager.org/download/sources/virt-manager/virt-manager-1.4.1.tar.gz
Already downloaded: /Users/username/Library/Caches/Homebrew/virt-manager-1.4.1.tar.gz
==> Patching
patching file virt-clone
patching file virt-convert
patching file virt-install
patching file virt-manager
patching file virt-xml
==> Downloading https://libvirt.org/sources/python/libvirt-python-3.4.0.tar.gz
Already downloaded: /Users/username/Library/Caches/Homebrew/virt-manager--libvirt-python-3.4.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/virt-manager/1.4.1/libexec/vendor --single
Last 15 lines from /Users/username/Library/Logs/Homebrew/virt-manager/01.python:
--prefix=/usr/local/Cellar/virt-manager/1.4.1/libexec/vendor
--single-version-externally-managed
--record=installed.txt

running install
running build
/usr/local/opt/pkg-config/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
/usr/bin/python generator.py libvirt /usr/local/Cellar/libvirt/3.7.0/share/libvirt/api/libvirt-api.xml
Found 428 functions in /usr/local/Cellar/libvirt/3.7.0/share/libvirt/api/libvirt-api.xml
Found 0 functions in libvirt-override-api.xml
Generated 348 wrapper functions
Missing type converters: 
unsigned long long *:1 
ERROR: failed virDomainMigrateGetMaxDowntime
error: command '/usr/bin/python' failed with exit status 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
brew install virt-manager issue https://github.com/jeffreywildman/homebrew-virt-manager/issues/58
virt-manager silently quits at launch https://github.com/jeffreywildman/homebrew-virt-manager/issues/78
installation failure for virt-manager https://github.com/jeffreywildman/homebrew-virt-manager/issues/72
Error: jeffreywildman/virt-manager/libvirt-glib 1.0.0 did not build https://github.com/jeffreywildman/homebrew-virt-manager/issues/79
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62
Add necessary quotes https://github.com/jeffreywildman/homebrew-virt-manager/pull/75
Missing type converters: unsigned long long *:1 ERROR: failed virDomainMigrateGetMaxDowntime error: command '/usr/bin/python' failed with exit status 1 https://github.com/jeffreywildman/homebrew-virt-manager/issues/84
ERROR: failed virDomainMigrateGetMaxDowntime error: command '/usr/bin/python' failed with exit status 1 https://github.com/jeffreywildman/homebrew-virt-manager/issues/81
Installation fails: Missing type converters: unsigned long long *:1 ERROR: failed virDomainMigrateGetMaxDowntime https://github.com/jeffreywildman/homebrew-virt-manager/issues/80
missing module gi https://github.com/jeffreywildman/homebrew-virt-manager/issues/76
enable audio/video streaming; overhaul build https://github.com/jeffreywildman/homebrew-virt-manager/pull/83
gi has no attribute 'require_version' https://github.com/jeffreywildman/homebrew-virt-manager/issues/74
Installation fails: Missing type converters https://github.com/jeffreywildman/homebrew-virt-manager/issues/71
Unable to connect to libvirt https://github.com/jeffreywildman/homebrew-virt-manager/issues/63
Unable to paste from host to client. Copying from client to host works. https://github.com/jeffreywildman/homebrew-virt-manager/issues/35
Can't install libvirt-python on El Capitan https://github.com/jeffreywildman/homebrew-virt-manager/issues/50
libvirt connection URI ?socket string https://github.com/jeffreywildman/homebrew-virt-manager/issues/61
Install error: failed virConnectNodeDeviceEventRegisterAny https://github.com/jeffreywildman/homebrew-virt-manager/issues/57
 libvirt-glib wont build - OSError: [Errno 1] Operation not permitted: g-ir-scanner/ https://github.com/jeffreywildman/homebrew-virt-manager/issues/82
Create new virtual machine OS types missing https://github.com/jeffreywildman/homebrew-virt-manager/issues/64
Error: configure: error: libjpeg not found https://github.com/jeffreywildman/homebrew-virt-manager/issues/49
after brew update  , the same error https://github.com/jeffreywildman/homebrew-virt-manager/issues/55
Crash on re-open VNC console https://github.com/jeffreywildman/homebrew-virt-manager/issues/44
Fresh install on 10.11.1: fatal error: 'glib/gi18n-lib.h' file not found https://github.com/jeffreywildman/homebrew-virt-manager/issues/30
Install error: [LibvirtGLib-1.0.gir] Error 1 https://github.com/jeffreywildman/homebrew-virt-manager/issues/77
Unable to install due to missing six python module. https://github.com/jeffreywildman/homebrew-virt-manager/issues/68
Python quit unexpectedly every time I try and select a drop down box. https://github.com/jeffreywildman/homebrew-virt-manager/issues/45
Docs update about remote connections https://github.com/jeffreywildman/homebrew-virt-manager/issues/42
Error installing spice-gtk: No package 'spice-client-glib-2.0' found https://github.com/jeffreywildman/homebrew-virt-manager/issues/56

**Comment by mastix** [comment] 2017-10-06 18:14
Same thing here... :(

**Comment by mastix** [comment] 2017-10-06 19:38
Just tried the pull request #85 and it fixes the issue.

**Comment by lunixbochs** [comment] 2017-10-08 16:57
https://github.com/jeffreywildman/homebrew-virt-manager/pull/83 should already fix this. It too upgrades to libvirt-python 3.7.0

**Comment by e0ne** [comment] 2017-11-05 19:15
Issue is still reproducible on the latest Mac OS

**Comment by cjedw** [comment] 2017-11-11 17:09
Same issue on Sierra 10.12.6

**Comment by jeffreywildman** [comment] 2018-02-25 02:27
Marking as a duplicate of #90, probably resolved by pull request in #83 or additional updates on master.

**Closed by jeffreywildman** 2018-02-25 02:27 UTC
