### ISSUE TITLE
installation failure for virt-manager

### ISSUE THREAD

**Issue by jonathangilpin** [jeffreywildman/homebrew-virt-manager#72] opened 2017-06-20 22:58 UTC
$ brew install virt-manager virt-viewer
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

==> Installing virt-manager from jeffreywildman/virt-manager
==> Downloading https://virt-manager.org/download/sources/virt-manager/virt-manager-1.4.1.tar.gz
Already downloaded: /Users/jonathangilpin/Library/Caches/Homebrew/virt-manager-1.4.1.tar.gz
==> Patching
patching file virt-clone
patching file virt-convert
patching file virt-install
patching file virt-manager
patching file virt-xml
==> Downloading https://libvirt.org/sources/python/libvirt-python-3.0.0.tar.gz
Already downloaded: /Users/jonathangilpin/Library/Caches/Homebrew/virt-manager--libvirt-python-3.0.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/virt-manager/1.4.1/libexec/vendor --single-version-externally-managed --record=installed.txt
Last 15 lines from /Users/jonathangilpin/Library/Logs/Homebrew/virt-manager/01.python:
running install
running build
/usr/local/opt/pkg-config/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
/usr/local/opt/python/bin/python2.7 generator.py libvirt /usr/local/Cellar/libvirt/3.4.0/share/libvirt/api/libvirt-api.xml
Found 425 functions in /usr/local/Cellar/libvirt/3.4.0/share/libvirt/api/libvirt-api.xml
Found 0 functions in libvirt-override-api.xml
Generated 348 wrapper functions
Missing type converters: 
virStreamSinkFunc:1 
long long *:1 
virStreamSourceFunc:1 
ERROR: failed virStreamRecvHole
ERROR: failed virStreamSparseRecvAll
ERROR: failed virStreamSparseSendAll
error: command '/usr/local/opt/python/bin/python2.7' failed with exit status 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jeffreywildman/homebrew-virt-manager/issues

These open issues may also help:
brew install virt-manager issue https://github.com/jeffreywildman/homebrew-virt-manager/issues/58
virt-manager crashing with Python quit unexpectedly while using the libgdk-3.0.dylib https://github.com/jeffreywildman/homebrew-virt-manager/issues/62

**Comment by rygjones** [comment] 2017-06-21 03:42
Same issue. Sierra 10.12.4.

**Comment by jonathangilpin** [comment] 2017-06-21 08:11
vi /usr/local/Homebrew/Library/Taps/jeffreywildman/homebrew-virt-manager/virt-manager.rb

change:
    url "https://libvirt.org/sources/python/libvirt-python-3.0.0.tar.gz"
to
    url "https://libvirt.org/sources/python/libvirt-python-3.4.0.tar.gz"

and
        sha256 "94a7c1c57a643afad43f9068c70774e1146ed051ecfca0280d5127011c5e44c1"
to
        sha256 "afa77781f518988f164dd5f99d1844034ca807a8e731e07cbae18474d250b511"


and it will then install however it will crash when you run it, unless you run with the argument ---debug

**Comment by opless** [comment] 2017-06-27 00:45
--debug works, as it implies --no-fork as it spews debugging info to stdout.

**Comment by veetow** [comment] 2018-02-13 19:34
I should add:
High Sierra 10.13.2
Python 2.7.10

**Comment by knewter** [comment] 2018-02-13 20:04
@veetow what good timing, I just ran into this bug as well :)

(now i want to know what you're using it for)

**Comment by dvj** [comment] 2018-02-13 21:36
I've tried updating to virt-manager-1.5.0.tar.gz and libvirt-python-4.0.0.tar.gz, which gets different results, but I haven't gotten everything to work after poking around for a few minutes.

**Comment by veetow** [comment] 2018-02-13 21:56
I think the real issue here is that the the install should NOT be using `/usr/bin/python` in the first place, but should be using the homebrew python install at `/usr/local/bin/python2`.

**Comment by veetow** [comment] 2018-02-13 21:58
FYI, this fixed it for me: #85

**Comment by veetow** [comment] 2018-02-13 22:04
Also, this after installing: #73

**Comment by jeffreywildman** [comment] 2018-02-25 02:55
Looks like a duplicate of #90 caused by mismatch of libvirt-python and libvirt versions. Should be addressed by pull request #83 and updates in master which now match versions at 4.0.0. Closing for now, but please open a new issue if it persists.

@veetow FYI, [homebrew conventions](https://github.com/Homebrew/brew/blob/master/docs/Python-for-Formula-Authors.md#python-declarations) prefer using system Python over a homebrewed Python. The updated `virt-manager` formula in master now uses a virtualenv to better keep the version used to build and run virt-manager separate from the Python version in the user's path. Also,  the `libvirt` formula is provided by homebrew-core but it doesn't appear to provide the associated Python bindings, which necessitates the `libvirt-python` dependency embedded within the `virt-manager` formula. When the `libvirt` version gets updated in homebrew, we have to play catch up and update the associated module in `virt-manager`. A proper fix would probably involve incorporating the python bindings to be built/installed with the `libvirt` formula.

**Closed by jeffreywildman** 2018-02-25 02:55 UTC

**Comment by omkensey** [comment] 2018-03-22 20:54
I just ran into this with a fresh install of homebrew in High Sierra.  Running the fix listed in #73 did not resolve it.
