### ISSUE TITLE
Install error: failed virConnectNodeDeviceEventRegisterAny

### ISSUE THREAD

**Issue by markabrahams** [jeffreywildman/homebrew-virt-manager#57] opened 2016-09-04 22:56 UTC
On installing virt-manager, I get the error:

MacBook:Downloads mark$ brew doctor
Your system is ready to brew.
MacBook:Downloads mark$ brew install virt-manager
==> Installing virt-manager from jeffreywildman/virt-manager
==> Downloading https://fedorahosted.org/released/virt-manager/virt-manager-1.4.0.tar.gz
Already downloaded: /Users/mark/Library/Caches/Homebrew/virt-manager-1.4.0.tar.gz
==> Patching
patching file virt-clone
patching file virt-convert
patching file virt-install
patching file virt-manager
patching file virt-xml
==> Downloading https://libvirt.org/sources/python/libvirt-python-2.1.0.tar.gz
Already downloaded: /Users/mark/Library/Caches/Homebrew/virt-manager--libvirt-python-2.1.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/virt-manager/1.4.0/libexec/vendor --single-version-externally-managed --record=installed.
Last 15 lines from /Users/mark/Library/Logs/Homebrew/virt-manager/01.python:
--prefix=/usr/local/Cellar/virt-manager/1.4.0/libexec/vendor
--single-version-externally-managed
--record=installed.txt

running install
running build
/usr/local/opt/pkg-config/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
/usr/bin/python generator.py libvirt /usr/local/Cellar/libvirt/2.2.0/share/libvirt/api/libvirt-api.xml
Found 415 functions in /usr/local/Cellar/libvirt/2.2.0/share/libvirt/api/libvirt-api.xml
Found 0 functions in libvirt-override-api.xml
Generated 344 wrapper functions
Missing type converters: 
virConnectNodeDeviceEventGenericCallback:1 
ERROR: failed virConnectNodeDeviceEventRegisterAny
error: command '/usr/bin/python' failed with exit status 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/jeffreywildman/homebrew-virt-manager/issues

**Comment by timm088** [comment] 2016-09-06 11:21
Same issue here, seemed to have occurred after I ran a clear and fresh install on brew.

**Comment by timm088** [comment] 2016-09-07 10:58
Pretty much tried everything I can on this one. Completely cleared every brew package.

Tried suggestions from #39 , no dice.
Same error every time.

```
Missing type converters:
virConnectNodeDeviceEventGenericCallback:1
ERROR: failed virConnectNodeDeviceEventRegisterAny
error: command '/usr/local/opt/python/bin/python2.7' failed with exit status 1
```

**Comment by tomgagnier** [comment] 2016-09-07 17:33
I am experiencing same issue.  

I am using the latest python distributed by home brew (2.7.2)

The install of virt-viewer works, btw. 

`
❯❯❯brew install virt-manager
==> Installing virt-manager from jeffreywildman/virt-manager
==> Downloading https://fedorahosted.org/released/virt-manager/virt-manager-1.4.0.tar.gz
Already downloaded: /Users/tgagnier/Library/Caches/Homebrew/virt-manager-1.4.0.tar.gz
==> Patching
patching file virt-clone
patching file virt-convert
patching file virt-install
patching file virt-manager
patching file virt-xml
==> Downloading https://libvirt.org/sources/python/libvirt-python-2.1.0.tar.gz
Already downloaded: /Users/tgagnier/Library/Caches/Homebrew/virt-manager--libvirt-python-2.1.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/virt-manager/1.4.0/libexec/vendor --single-version-externally-managed --re
Last 15 lines from /Users/tgagnier/Library/Logs/Homebrew/virt-manager/01.python:
--prefix=/usr/local/Cellar/virt-manager/1.4.0/libexec/vendor
--single-version-externally-managed
--record=installed.txt

running install
running build
/usr/local/opt/pkg-config/bin/pkg-config --print-errors --atleast-version=0.9.11 libvirt
/usr/local/opt/python/bin/python2.7 generator.py libvirt /usr/local/Cellar/libvirt/2.2.0/share/libvirt/api/libvirt-api.xml
Found 415 functions in /usr/local/Cellar/libvirt/2.2.0/share/libvirt/api/libvirt-api.xml
Found 0 functions in libvirt-override-api.xml
Generated 344 wrapper functions
Missing type converters:
virConnectNodeDeviceEventGenericCallback:1
ERROR: failed virConnectNodeDeviceEventRegisterAny
error: command '/usr/local/opt/python/bin/python2.7' failed with exit status 1
`

**Comment by wparam-fox** [comment] 2016-09-07 17:38
I was able to install this just fine, but that seems to be because I generally don't update brew (or anything else, unless it's broken).  My build was from july 11th.  I have been able to get this to work on a clean system, starting from a clean brew install, with the following commands:  (Do these after you install, after you brew tap the virt-manager keg, but BEFORE you do anything else.)

cd /usr/local/Library/Taps/homebrew/homebrew-core/
git fetch --depth 4500
git checkout 277a4fe16f2a0622be312a4bbe0098fa8f3c38dc

cd /usr/local/Library/Taps/jeffreywildman/homebrew-virt-manager/
git fetch --unshallow
git checkout 335e5a81df2df4bc5368c70e59ead6d5c0a7bd31

cd /usr/local
git fetch --unshallow
git checkout c65be8879d4fc99b120701f2128520c92860c4f0

This updates those three locations to roughly around the time of july 11th, which is where my build came from.  It will get you a lot of old stuff, though.  I haven't yet tried to do a brew upgrade of things on my system, and I wouldn't be surprised if that makes things explode.  But, if you've got an emergency where you need virt-manager RTFN, this will hopefully help.

The trouble seems to come from something which is separate from the virt manager packages, because nuking your cache and running these commands, AFTER you see the failure, does not improve things.

I've attached two brew list outputs, one from the clean VM with the above commands run (virt-working), and one from brew latest where it failed.  I suspect somewhere in the diff of the two is the package that's hosing us, assuming it's not libvirt itself.
[virt-failed.txt](https://github.com/jeffreywildman/homebrew-virt-manager/files/459899/virt-failed.txt) 
[virt-working.txt](https://github.com/jeffreywildman/homebrew-virt-manager/files/459900/virt-working.txt)

**Comment by tomgagnier** [comment] 2016-09-07 18:44
Thank you for the script and instructions.  They work!

I had to uninstall and untap all virt packages, re-tap and re-install.

**Comment by wparam-fox** [comment] 2016-09-07 19:44
Combining the advice of @tomgagnier with what I had, this sequence of commands seems to work even after you've tried and failed, and as far as I can tell, doesn't leave brew in a wonky state.  These commands are intended to be run after you've already tried the brew install virt-manager and had it fail.  It will install several older versions alongside what you have, and should get to the end ok.  After it finishes, and you're back on `master`, `brew outdated` will show libvirt and shared-mime-info in addition to whatever else you haven't upgraded.  I have successfully run `brew upgrade` on this, and the commands complete, and virt-manager still works.  I've even run `brew cleanup`, and things don't fall over.  So I'm cautiously optimistic.

```brew remove libvirt
brew remove libvirt-glib
brew untap jeffreywildman/virt-manager
brew tap jeffreywildman/homebrew-virt-manager

cd /usr/local/Library/Taps/homebrew/homebrew-core/
git fetch --depth 4500
git checkout 277a4fe16f2a0622be312a4bbe0098fa8f3c38dc

cd /usr/local/Library/Taps/jeffreywildman/homebrew-virt-manager/
git fetch --unshallow
git checkout 335e5a8

cd /usr/local
git fetch --unshallow
git checkout c65be8879d4fc99b120701f2128520c92860c4f0

brew install virt-manager virt-viewer

cd /usr/local/Library/Taps/homebrew/homebrew-core/
git checkout master

cd /usr/local/Library/Taps/jeffreywildman/homebrew-virt-manager/
git checkout master

cd /usr/local
git checkout master

brew update```
After that, optionally:
```brew upgrade
brew cleanup```

**Comment by timm088** [comment] 2016-09-08 05:52
@tomgagnier @wparam-fox awesome stuff, works here, no more errors.
Including the optional steps. Cheers!

**Comment by myMartek** [comment] 2016-09-15 11:00
If I follow your workaround I get an error, that there is a libtiff patch not available which is because of that older version of homebrew core I guess.

**Comment by Nethe** [comment] 2016-09-20 11:11
I followed steps above (tomgagnier) and it worked. Thanks.

**Comment by fsoppelsa** [comment] 2016-09-20 13:41
With latest Xcode and after `brew upgrade` I still have the issue

```
Missing type converters: 
virConnectNodeDeviceEventGenericCallback:1 
ERROR: failed virConnectNodeDeviceEventRegisterAny
error: command '/usr/local/opt/python/bin/python2.7' failed with exit status 1
```

I tried the workaround above, no success.

BTW, what's the directory where to `git fetch --unshallow` at step 3?

**Comment by Nethe** [comment] 2016-09-20 14:33
>fsoppelsa 
I did it in 

`/usr/local/Homebrew/`

**Comment by fsoppelsa** [comment] 2016-09-20 15:22
Thanks @Nethe works :)

**Comment by myMartek** [comment] 2016-09-21 05:47
Fails for me with

`==> Installing jeffreywildman/virt-manager/virt-manager dependency: libtiff
==> Downloading http://download.osgeo.org/libtiff/tiff-4.0.6.tar.gz
######################################################################## 100,0%
==> Downloading https://mirrors.ocf.berkeley.edu/debian/pool/main/t/tiff/tiff_4.0.6-1.debian.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://mirrorservice.org/sites/ftp.debian.org/debian/pool/main/t/tiff/tiff_4.0.6-1.debian.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "libtiff--patch"
Download failed: https://mirrorservice.org/sites/ftp.debian.org/debian/pool/main/t/tiff/tiff_4.0.6-1.debian.tar.xz`

**Comment by ki-media** [comment] 2016-09-21 19:49
Same here. Workaround not working anymore with above errors.

**Comment by Ryuchen** [comment] 2016-09-22 01:25
Same here no solutions found yet.

**Comment by Nethe** [comment] 2016-09-22 16:58
@ki-media @Ryuchen 

I just tested the steps shown above, and I must say it is working. I am working on OSX Sierra. 
Please try to follow steps/commands below: (i know, i am repeating previous reply, but my paths are little bit different)

`cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core`
`git fetch --depth 4500`
`git checkout 277a4fe16f2a0622be312a4bbe0098fa8f3c38dc`

`/usr/local/Homebrew/Library/Taps/jeffreywildman/homebrew-virt-manager`
`git fetch --unshallow`
`git checkout 335e5a8`

`cd /usr/local/Homebrew`
`git fetch --unshallow`
`git checkout c65be8879d4fc99b120701f2128520c92860c4f0`

**I also had to do (it was Homebrew's request):**
`brew link intltool dbus xz pcre jpeg pixman cairo gobject-introspection gdk-pixbuf atk libepoxy hicolor-icon-theme gsettings-desktop-schemas gnome-icon-theme gmp nettle wget check glib-networking vala libsoup py2cairo pygobject3 libosinfo yajl libvirt-glib libusb usbredir spice-gtk vte3`

Once steps above are finished, you can start the **virt-manager and virt-viewer installation** using command below:

`brew install virt-manager virt-viewer`

It should work. If not, please paste the output with errors.

**Comment by ki-media** [comment] 2016-09-23 20:03
@Nethe 
Sure I noticed the paths above were wrong. I corrected them as you did. Just tried your Approach again. Same Errors:

"==> Downloading https://mirrors.ocf.berkeley.edu/debian/pool/main/t/tiff/tiff_4.0.6-1.debian.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://mirrorservice.org/sites/ftp.debian.org/debian/pool/main/t/tiff/tiff_4.0.6-1.debian.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "libtiff--patch"
Download failed: https://mirrorservice.org/sites/ftp.debian.org/debian/pool/main/t/tiff/tiff_4.0.6-1.debian.tar.xz"

**Comment by deathlord87** [comment] 2016-09-23 20:41
I'm having the same trouble as above after trying the same thing on OSX Sierra.

**Comment by p0ns** [comment] 2016-09-24 01:30
Fixed that last libtiff error using git checkout d58f19cfe052ee357ad6885d62ee7fca8c264cf3 on homebrew-core

**Comment by danifunker** [comment] 2016-09-24 01:39
I resolved that issue by install jpeg 

brew install jpeg 
followed by
brew install lib tiff

**Comment by Ryuchen** [comment] 2016-09-24 06:44
@p0ns 
I follow you steps but I got the following error:
==> Installing jeffreywildman/virt-manager/virt-manager dependency: libcroco
==> Downloading https://download.gnome.org/sources/libcroco/0.6/libcroco-0.6.11.tar.xz
==> Downloading from http://ftp.nara.wide.ad.jp/pub/X11/GNOME/sources/libcroco/0.6/libcro
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/libcroco/0.6.11 --disable-Bsymbolic
Last 15 lines from /Users/ryu/Library/Logs/Homebrew/libcroco/01.configure:
checking whether to build gtk-doc documentation... no
checking for GTKDOC_DEPS... yes
checking for CROCO... no
configure: error: Package requirements (
  glib-2.0 >= 2.0
  libxml-2.0 >= 2.4.23) were not met:

No package 'libxml-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables CROCO_CFLAGS
and CROCO_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.

**Comment by flexgames** [comment] 2016-10-24 22:38
> git checkout 277a4fe16f2a0622be312a4bbe0098fa8f3c38dc

This ^ doesn't work for me.
I get 
> fatal: reference is not a tree: 277a4fe16f2a0622be312a4bbe0098fa8f3c38dc

Any suggestions? Thanks

**Comment by jeffreywildman** [comment] 2018-02-25 02:24
Original issue looks like a duplicate of #90 and shows a mismatch of libvirt-python and libvirt versions. Should be addressed on master now. Please try to reinstall and open a new issue if it reoccurs.

**Closed by jeffreywildman** 2018-02-25 02:24 UTC
