### ISSUE TITLE
error: libjpeg not found

### ISSUE THREAD

**Issue by ganganiashish** [jeffreywildman/homebrew-virt-manager#126] opened 2019-04-04 06:54 UTC
brew install virt-viewer

checking for the autoaudiosrc GStreamer element... yes
checking for GSTVIDEO... yes
checking for gst-inspect-1.0... (cached) /usr/local/opt/gstreamer/bin/gst-inspect-1.0
checking for the appsrc GStreamer element... no
checking for the videoconvert GStreamer element... no
checking for the appsink GStreamer element... (cached) no
checking for the jpegdec GStreamer element... yes
checking for the vp8dec GStreamer element... yes
checking for the vp9dec GStreamer element... yes
checking for the h264parse GStreamer element... no
checking for the h265parse GStreamer element... no
checking for the avdec_h264 GStreamer element... yes
checking for the avdec_h265 GStreamer element... yes
checking for jpeg_destroy_decompress in -ljpeg... no
configure: error: libjpeg not found

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/jeffreywildman/homebrew-virt-manager/issues

brew info libjpeg
jpeg: stable 9c (bottled)
Image manipulation library
https://www.ijg.org/
/usr/local/Cellar/jpeg/9c (21 files, 733.4KB)
  Poured from bottle on 2019-04-04 at 12:07:56
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/jpeg.rb
==> Analytics
install: 116,965 (30 days), 335,690 (90 days), 1,410,528 (365 days)
install_on_request: 4,908 (30 days), 15,324 (90 days), 72,688 (365 days)
build_error: 0 (30 days)

**Comment by jeffreywildman** [comment] 2019-05-25 13:36
Looks like the configure output from `spice-gtk` and not `virt-viewer`. Does `brew install spice-gtk` result in the same error?

**Comment by Amar1729** [comment] 2019-07-28 04:37
Not sure if this is working for @ganganiashish yet, but I just installed `spice-gtk`, `virt-manager`, and `virt-viewer` and they seem to build+install fine. 

darwin 10.14.5 (mojave), virt-manager version 2.2.1, spice-gtk version 0.37

**Comment by jeffreywildman** [comment] 2019-09-01 16:43
Closing, unable to reproduce on my system, others report successful installation, and not enough info to debug further.

**Closed by jeffreywildman** 2019-09-01 16:43 UTC
